version: 1.0.{build}

image: Visual Studio 2017

environment:
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
    - CMAKE_PLATFORM: "Visual Studio 15 2017"
    - CMAKE_PLATFORM: "Visual Studio 15 2017 Win64"

platform: x64
configuration: 
  - Release
  - Debug

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_PLATFORM%" ..
  - cmake --build . --target install --config %CONFIGURATION%
